version: "3"

services:
  app:
    build:
      context: aiauto
    command: gunicorn --bind 0.0.0.0:5000 app:app
    
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/nginx.conf.ro
    depends_on:
      - app
    ports:
      - "80:80"
