version: "3"

services:
  app:
    build:
      context: AIAutograder
    command: gunicorn app:app --bind 0.0.0.0:5000
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/nginx.conf.ro
    depends_on:
      - app
    ports:
      - "80:80"
